sonar.python.coverage.reportPaths=coverage.xml

sonar.projectKey=montymobile1_montyesim-eshop-api-testing
sonar.organization=montymobile1

sonar.exclusions= **/*.sql, **/*.yml

sonar.issue.ignore.multicriteria=e1

sonar.issue.ignore.multicriteria.e1.ruleKey=python:S7503
