create table device
(
    id                bigint generated by default as identity
        primary key,
    user_id           uuid
        references auth.users(id),
    device_id         varchar                 not null,
    fcm_token         varchar,
    manufacturer      varchar,
    device_model      varchar,
    os                varchar,
    os_version        varchar,
    app_version       varchar,
    ram_size          varchar,
    screen_resolution varchar,
    is_rooted         boolean,
    is_logged_in      boolean                 not null,
    originated_ip     varchar,
    ip_location       varchar,
    timestamp_login   timestamp,
    timestamp_logout  timestamp,
    created_at        timestamp default now() not null,
    updated_at        timestamp default now() not null,
    constraint unique_device_user
        unique (device_id, user_id)
);

comment
on table device is 'List of user devices';

alter table device
    owner to postgres;

grant select, update, usage on sequence device_id_seq to anon;

grant select, update, usage on sequence device_id_seq to authenticated;

grant select, update, usage on sequence device_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on device to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on device to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on device to service_role;

create table contact_us
(
    id         bigint generated by default as identity
        primary key,
    email      varchar,
    content    varchar,
    created_at timestamp default now() not null
);

alter table contact_us
    owner to postgres;

grant select, update, usage on sequence contact_us_id_seq to anon;

grant select, update, usage on sequence contact_us_id_seq to authenticated;

grant select, update, usage on sequence contact_us_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on contact_us to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on contact_us to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on contact_us to service_role;

create table notification
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp default now() not null,
    title      text,
    content    text,
    status     boolean,
    updated_at timestamp default now(),
    data       text,
    user_id    uuid
        references auth.users(id),
    image_url  varchar
);

alter table notification
    owner to postgres;

grant select, update, usage on sequence notification_id_seq to anon;

grant select, update, usage on sequence notification_id_seq to authenticated;

grant select, update, usage on sequence notification_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on notification to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on notification to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on notification to service_role;

create table users_copy
(
    id       uuid not null
        primary key,
    email    text
        unique,
    metadata jsonb
);

alter table users_copy
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on users_copy to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on users_copy to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on users_copy to service_role;

create table app_config
(
    id         bigint generated by default as identity
        primary key,
    key        varchar                                not null
        unique,
    value      text                                   not null,
    created_at timestamp with time zone default now() not null
);

alter table app_config
    owner to postgres;

grant select, update, usage on sequence app_config_id_seq to anon;

grant select, update, usage on sequence app_config_id_seq to authenticated;

grant select, update, usage on sequence app_config_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on app_config to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on app_config to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on app_config to service_role;

create table promotion_rule_action
(
    id   smallint not null
        primary key,
    name varchar(30)
);

alter table promotion_rule_action
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_action to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_action to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_action to service_role;

create table promotion_rule_event
(
    id   smallint not null
        primary key,
    name varchar(30)
);

alter table promotion_rule_event
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_event to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_event to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule_event to service_role;

create table promotion_rule
(
    id                       uuid      default gen_random_uuid() not null
        primary key,
    promotion_rule_action_id integer                             not null
        references promotion_rule_action,
    promotion_rule_event_id  integer                             not null
        references promotion_rule_event,
    max_usage                integer   default 1                 not null,
    beneficiary              integer   default 0
        constraint promotion_rule_beneficiary_check
            check (beneficiary = ANY (ARRAY[0, 1, 2])),
    created_at               timestamp default now(),
    id_text                  text generated always as ((id)::text
) stored,
    name                     text      default ''::text
);

comment
on column promotion_rule.name is 'rule name combination of :action,event,max usage';

alter table promotion_rule
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_rule to service_role;

create table promotion
(
    id          uuid         default gen_random_uuid() not null
        primary key,
    rule_id     uuid                                   not null
        references promotion_rule,
    code        varchar(50)                            not null
        unique
        constraint promotion_code_check
            check (length(TRIM(BOTH FROM (code)::text)) >= 2),
    bundle_code varchar(200) default NULL::character varying,
    type        varchar(50),
    amount      real         default 0
        constraint promotion_amount_check
            check (amount > (0):: double precision
) ,
    callback_url     text,
    callback_headers text,
    valid_from       timestamp,
    valid_to         timestamp,
    is_active        boolean      default true,
    times_used       integer      default 0,
    created_at       timestamp    default now(),
    name             varchar
        unique
        constraint promotion_name_check
            check (length(TRIM(BOTH FROM (name)::text)) >= 2)
);

alter table promotion
    owner to postgres;

create table user_order
(
    id                  uuid        default gen_random_uuid() not null
        constraint user_bundle_order_pkey
            primary key,
    user_id             uuid        default auth.uid()        not null
        constraint user_bundle_order_user_id_fkey
            references auth.users(id),
    esim_order_id       varchar,
    bundle_id           varchar,
    amount              numeric                               not null,
    currency            varchar                               not null,
    order_type          varchar     default 'assign'::character varying  not null,
    payment_status      varchar     default 'pending'::character varying not null,
    order_status        varchar     default 'pending'::character varying not null,
    payment_time        timestamp,
    created_at          timestamp   default now()             not null,
    callback_time       timestamp,
    bundle_data         text,
    searched_countries  varchar,
    anonymous_user_id   uuid        default auth.uid()
        constraint user_bundle_order_anonymous_user_fkey
            references auth.users(id),
    payment_intent_code varchar,
    promo_code          varchar(50) default NULL::character varying
        references promotion (code),
    referral_code       varchar(50) default NULL::character varying,
    modified_amount     decimal,
    otp                 varchar,
    payment_type        varchar(100) default null,
    otp_expired_at      timestamp default null
);

alter table user_order
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_order to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_order to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_order to service_role;

create table user_profile
(
    id                 uuid                     default gen_random_uuid() not null
        primary key,
    user_id            uuid                     default auth.uid()
        references auth.users(id),
    user_order_id      uuid                                               not null
        references user_order,
    iccid              varchar(100)                                       not null,
    smdp_address       varchar(100)                                       not null,
    validity           varchar(100),
    created_at         timestamp with time zone default now()             not null,
    label              varchar(200),
    activation_code    varchar(200)                                       not null,
    allow_topup        boolean                  default false             not null,
    esim_hub_order_id  varchar(200),
    searched_countries varchar(200),
    shared_user_id     uuid                     default gen_random_uuid()
);

alter table user_profile
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile to service_role;

create table user_profile_bundle
(
    id                bigint generated by default as identity
        constraint user_bundle_pkey
            primary key,
    user_id           uuid         default auth.uid() not null
        constraint user_bundle_user_id_fkey
            references auth.users(id),
    user_order_id     uuid                            not null
        constraint user_bundle_user_order_id_fkey
            references user_order,
    plan_started      boolean      default false      not null,
    bundle_expired    boolean      default false      not null,
    created_at        timestamp    default now()      not null,
    bundle_type       varchar(100) default 'Primary Bundle'::character varying not null,
    bundle_data       jsonb                           not null,
    iccid             varchar,
    user_profile_id   uuid                            not null
        references user_profile,
    esim_hub_order_id varchar
);

alter table user_profile_bundle
    owner to postgres;

grant select, update, usage on sequence user_profile_bundle_id_seq to anon;

grant select, update, usage on sequence user_profile_bundle_id_seq to authenticated;

grant select, update, usage on sequence user_profile_bundle_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile_bundle to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile_bundle to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_profile_bundle to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion to service_role;

create table promotion_usage
(
    id             uuid default gen_random_uuid() not null
        primary key,
    user_id        uuid,
    promotion_code varchar
        references promotion (code),
    referral_code  varchar,
    amount         real default 0
        constraint promotion_usage_amount_check
            check (amount >= (0):: double precision
) ,
    status         varchar(20) default 'pending'::character varying not null
        constraint promotion_usage_status_check
            check ((status)::text = ANY
                   ((ARRAY ['pending'::character varying, 'completed'::character varying, 'failed'::character varying])::text[])),
    created_at     timestamp   default now(),
    bundle_id      uuid,
    device_id      varchar(250),
    referred_to    varchar,
    order_id       uuid
);

alter table promotion_usage
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_usage to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_usage to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on promotion_usage to service_role;

create table user_wallet
(
    id      uuid default gen_random_uuid() not null
        primary key,
    user_id uuid                           not null
        references auth.users(id)
        on delete cascade,
    amount  numeric default 0
        constraint user_wallet_amount_check
            check (amount >= (0):: double precision
) ,
    currency   varchar(10)                         not null,
    created_at timestamp default now(),
    updated_at timestamp default now()
);

alter table user_wallet
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet to service_role;

create table user_wallet_transaction
(
    id        uuid default gen_random_uuid() not null
        primary key,
    wallet_id uuid                           not null
        references user_wallet
            on delete cascade,
    amount    numeric                        not null,
    status    varchar(10)                    not null
        constraint user_wallet_transaction_status_check
            check ((status)::text = ANY
        ((ARRAY ['success':: character varying, 'failed':: character varying, 'pending':: character varying])::text[])
) ,
    source     varchar(50)                         not null,
    created_at timestamp default now(),
    updated_at timestamp default now()
);

alter table user_wallet_transaction
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet_transaction to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet_transaction to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on user_wallet_transaction to service_role;

create table bundle
(
    id          uuid      default gen_random_uuid() not null
        primary key,
    data        jsonb,
    is_active   boolean   default true,
    created_at  timestamp default now(),
    updated_at  timestamp default now(),
    bundle_name text
        constraint bundle_bundle_name_check
            check (length(bundle_name) < 100),
    constraint bundle_check
        check (length('bundle_name'::text) <= 60)
);

comment
on column bundle.bundle_name is 'this field will be used as display title in subscriber, without touching the data inside data json object as it is from sync';

alter table bundle
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle to service_role;

create table tag_group
(
    id             bigint generated by default as identity
        primary key,
    name           varchar(300)
        unique
        constraint tag_group_name_check
            check (length((name)::text) < 30),
    type           integer not null,
    is_active      boolean   default true,
    created_at     timestamp default now(),
    updated_at     timestamp default now(),
    group_category varchar
);

alter table tag_group
    owner to postgres;

grant select, update, usage on sequence tag_group_id_seq to anon;

grant select, update, usage on sequence tag_group_id_seq to authenticated;

grant select, update, usage on sequence tag_group_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_group to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_group to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_group to service_role;

create table tag
(
    id           uuid      default gen_random_uuid() not null
        primary key,
    tag_group_id bigint                              not null
        references tag_group
            on delete cascade,
    name         varchar(300)                        not null,
    icon         varchar(300),
    data         jsonb,
    created_at   timestamp default now(),
    updated_at   timestamp default now(),
    constraint unique_tag_name_per_group
        unique (name, tag_group_id)
);

alter table tag
    owner to postgres;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag to service_role;

create table bundle_tag
(
    id         bigint generated by default as identity
        primary key,
    bundle_id  uuid not null
        references bundle,
    tag_id     uuid not null
        references tag,
    is_active  boolean   default true,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    constraint unique_bundle_tag
        unique (bundle_id, tag_id)
);

alter table bundle_tag
    owner to postgres;

grant select, update, usage on sequence bundle_tag_id_seq to anon;

grant select, update, usage on sequence bundle_tag_id_seq to authenticated;

grant select, update, usage on sequence bundle_tag_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle_tag to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle_tag to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on bundle_tag to service_role;

create table currency
(
    id               bigint generated by default as identity
        primary key,
    name             varchar(300),
    rate             real         not null,
    default_currency varchar(300) not null,
    created_at       timestamp default now(),
    updated_at       timestamp default now()
);

alter table currency
    owner to postgres;

grant select, update, usage on sequence currency_id_seq to anon;

grant select, update, usage on sequence currency_id_seq to authenticated;

grant select, update, usage on sequence currency_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on currency to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on currency to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on currency to service_role;

create table voucher
(
    id         bigint generated by default as identity
        primary key,
    code       varchar(300)
        unique,
    amount     real                    not null,
    is_used    boolean   default false not null,
    is_active  boolean   default true  not null,
    used_by    uuid,
    created_at timestamp default now(),
    updated_at timestamp default now(),
    expired_at timestamp
);

alter table voucher
    owner to postgres;

grant select, update, usage on sequence voucher_id_seq to anon;

grant select, update, usage on sequence voucher_id_seq to authenticated;

grant select, update, usage on sequence voucher_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on voucher to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on voucher to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on voucher to service_role;

create table tag_translation
(
    id         bigint generated by default as identity
        primary key,
    tag_id     uuid,
    locale     varchar(30) default 'en'::character varying not null,
    name       varchar(500) not null,
    data       jsonb,
    created_at timestamp   default now(),
    updated_at timestamp   default now()
);

alter table tag_translation
    owner to postgres;

grant select, update, usage on sequence tag_translation_id_seq to anon;

grant select, update, usage on sequence tag_translation_id_seq to authenticated;

grant select, update, usage on sequence tag_translation_id_seq to service_role;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_translation to anon;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_translation to authenticated;

grant
delete
, insert, references,
select, trigger, truncate,
update
on tag_translation to service_role;

create table banner
(
    id          serial
        primary key,
    title       varchar,
    description varchar,
    action      varchar,
    image       varchar,
    created_at  timestamp default CURRENT_TIMESTAMP,
    platform    varchar
);

alter table banner
    owner to postgres;

create function update_timestamp() returns trigger
    language plpgsql
as
$$
BEGIN
    NEW.updated_at
= NOW();
RETURN NEW;
END;
$$;

alter function update_timestamp() owner to postgres;

grant
execute
on
function
update_timestamp
() to anon;

grant execute on function update_timestamp
() to authenticated;

grant execute on function update_timestamp
() to service_role;

create function sync_users_copy() returns trigger security definer
    language plpgsql
as
$$
BEGIN
    -- Handle INSERT
    IF
TG_OP = 'INSERT' THEN
        INSERT INTO public.users_copy (id, email, metadata)
        VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data)
        ON CONFLICT (id) DO NOTHING;

    -- Handle UPDATE
    ELSIF
TG_OP = 'UPDATE' THEN
UPDATE public.users_copy
SET email    = NEW.email,
    metadata = NEW.raw_user_meta_data
WHERE id = NEW.id;

-- Handle DELETE
ELSIF
TG_OP = 'DELETE' THEN
DELETE
FROM public.users_copy
WHERE id = OLD.id;
END IF;

RETURN NEW;
END;
$$;

alter function sync_users_copy() owner to postgres;

grant
execute
on
function
sync_users_copy
() to anon;

grant execute on function sync_users_copy
() to authenticated;

grant execute on function sync_users_copy
() to service_role;

create function insert_group_with_tags(_name text, _group_category text, _type integer, _tags jsonb) returns json
    language plpgsql
as
$$
declare
inserted_group tag_group;
  tag
jsonb;
begin
insert into tag_group (name, group_category, type)
values (_name, _group_category, _type) returning *
into inserted_group;

-- Insert tags
for tag in
select *
from jsonb_array_elements(_tags) loop
    insert
into tag (name, icon, tag_group_id)
values (
    tag->>'name', tag->>'icon', inserted_group.id
    );
end loop;

return json_build_object('group', inserted_group);

exception
  when others then
    raise notice 'Rollback due to error: %', sqlerrm;
    -- No need for explicit ROLLBACK; PostgreSQL will auto-rollback the function on exception
return json_build_object('error', sqlerrm);
end;
$$;

alter function insert_group_with_tags(text, text, integer, jsonb) owner to postgres;

grant
execute
on
function
insert_group_with_tags
(text, text, integer, jsonb) to anon;

grant execute on function insert_group_with_tags
(text, text, integer, jsonb) to authenticated;

grant execute on function insert_group_with_tags
(text, text, integer, jsonb) to service_role;

create function delete_group_if_no_bundles(_group_id uuid) returns json
    language plpgsql
as
$$
declare
conflicting_bundles json;
begin
  -- Get all bundles associated via bundle_tag → tag → group
select json_agg(json_build_object(
        'bundle_id', b.id,
        'bundle_name', b.name
                ))
into conflicting_bundles
from bundle_tag bt
         join tag t on t.id = bt.tag_id
         join bundle b on b.id = bt.bundle_id
where t.tag_group_id = _group_id;

-- If bundles are found, return error
if
conflicting_bundles is not null then
    return json_build_object(
      'error', 'Cannot delete group: some tags are associated with bundles',
      'code', 500,
      'bundles', conflicting_bundles
    );
end if;

  -- Safe to delete group
delete
from tag_group
where id = _group_id;

return json_build_object('success', true);
exception
  when others then
    return json_build_object('error', sqlerrm, 'code', 500);
end;
$$;

alter function delete_group_if_no_bundles(uuid) owner to postgres;

grant
execute
on
function
delete_group_if_no_bundles
(uuid) to anon;

grant execute on function delete_group_if_no_bundles
(uuid) to authenticated;

grant execute on function delete_group_if_no_bundles
(uuid) to service_role;

create function delete_group_if_no_bundles(_group_id integer) returns json
    language plpgsql
as
$$
declare
conflicting_bundles json;
begin
  -- Get all bundles associated via bundle_tag → tag → group
select json_agg(json_build_object(
        'bundle_id', b.id,
        'bundle_name', b.name
                ))
into conflicting_bundles
from bundle_tag bt
         join tag t on t.id = bt.tag_id
         join bundle b on b.id = bt.bundle_id
where t.tag_group_id = _group_id;

-- If bundles are found, return error
if
conflicting_bundles is not null then
    return json_build_object(
      'error', 'Cannot delete group: some tags are associated with bundles',
      'code', 500,
      'bundles', conflicting_bundles
    );
end if;

  -- Safe to delete group
delete
from tag_group
where id = _group_id;

return json_build_object('success', true);
exception
  when others then
    return json_build_object('error', sqlerrm, 'code', 500);
end;
$$;

alter function delete_group_if_no_bundles(integer) owner to postgres;

grant
execute
on
function
delete_group_if_no_bundles
(integer) to anon;

grant execute on function delete_group_if_no_bundles
(integer) to authenticated;

grant execute on function delete_group_if_no_bundles
(integer) to service_role;

create function delete_group_if_no_bundle(_group_id integer) returns json
    language plpgsql
as
$$
declare
bundle_count integer;
begin
  -- Count bundles associated via bundle_tag → tag → group
select count(*)
into bundle_count
from bundle_tag bt
         join tag t on t.id = bt.tag_id
where t.tag_group_id = _group_id;

-- If bundles are found, return error
if
bundle_count > 0 then
    return json_build_object(
      'error', 'Cannot delete group: some tags are associated with bundles',
      'code', 'linked-bundles',
      'bundle_count', bundle_count
    );
end if;

  -- Safe to delete group
delete
from tag_group
where id = _group_id;

return json_build_object('success', true);
exception
  when others then
    return json_build_object('error', sqlerrm, 'code', 500);
end;
$$;

alter function delete_group_if_no_bundle(integer) owner to postgres;

grant
execute
on
function
delete_group_if_no_bundle
(integer) to anon;

grant execute on function delete_group_if_no_bundle
(integer) to authenticated;

grant execute on function delete_group_if_no_bundle
(integer) to service_role;

create function edit_tag_groups(p_id integer, p_name text, p_type text, p_group_category text, p_new_tags jsonb,
                                p_updated_tags jsonb, p_deleted_tag_ids uuid[]) returns void
    language plpgsql
as
$$
begin
  -- Step 1: Update the tag group
update tag_group
set name           = p_name,
    type           = p_type,
    group_category = p_group_category
where id = p_id;

-- Step 2: Delete tags by IDs
if
array_length(p_deleted_tag_ids, 1) is not null then
delete
from tag
where id = any (p_deleted_tag_ids);
end if;

  -- Step 3: Insert new tags
insert into tag (name, icon, tag_group_id)
select t ->>'name', t->>'icon', p_id
from jsonb_array_elements(p_new_tags) as t;

-- Step 4: Update existing tags
update tag
set name = t.value ->>'name', icon = t.value->>'icon'
from jsonb_array_elements(p_updated_tags)
with ordinality as t(value, idx)
where tag.id::text = t.value->>'id';

end;
$$;

alter function edit_tag_groups(integer, text, text, text, jsonb, jsonb, uuid[]) owner to postgres;

grant
execute
on
function
edit_tag_groups
(integer, text, text, text, jsonb, jsonb, uuid[]) to anon;

grant execute on function edit_tag_groups
(integer, text, text, text, jsonb, jsonb, uuid[]) to authenticated;

grant execute on function edit_tag_groups
(integer, text, text, text, jsonb, jsonb, uuid[]) to service_role;

create function edit_tag_groups(p_id integer, p_name text, p_type integer, p_group_category text, p_new_tags jsonb,
                                p_updated_tags jsonb, p_deleted_tag_ids uuid[]) returns void
    language plpgsql
as
$$
begin
  -- Step 1: Update the tag group
update tag_group
set name           = p_name,
    type           = p_type,
    group_category = p_group_category
where id = p_id;

-- Step 2: Delete tags by IDs
if
array_length(p_deleted_tag_ids, 1) is not null then
delete
from tag
where id = any (p_deleted_tag_ids);
end if;

  -- Step 3: Insert new tags
insert into tag (name, icon, tag_group_id)
select t ->>'name', t->>'icon', p_id
from jsonb_array_elements(p_new_tags) as t;

-- Step 4: Update existing tags
update tag
set name = t.value ->>'name', icon = t.value->>'icon'
from jsonb_array_elements(p_updated_tags)
with ordinality as t(value, idx)
where tag.id::text = t.value->>'id';

end;
$$;

alter function edit_tag_groups(integer, text, integer, text, jsonb, jsonb, uuid[]) owner to postgres;

grant
execute
on
function
edit_tag_groups
(integer, text, integer, text, jsonb, jsonb, uuid[]) to anon;

grant execute on function edit_tag_groups
(integer, text, integer, text, jsonb, jsonb, uuid[]) to authenticated;

grant execute on function edit_tag_groups
(integer, text, integer, text, jsonb, jsonb, uuid[]) to service_role;

create function edit_tag_group(p_id integer, p_name text, p_type integer, p_group_category text, p_new_tags jsonb,
                               p_updated_tags jsonb, p_deleted_tag_ids uuid[]) returns void
    language plpgsql
as
$$
begin
  -- Step 1: Update the tag group
update tag_group
set name           = p_name,
    type           = p_type,
    group_category = p_group_category
where id = p_id;

-- Step 2: Delete tags by IDs
if
array_length(p_deleted_tag_ids, 1) is not null then
delete
from tag
where id = any (p_deleted_tag_ids);
end if;

  -- Step 3: Insert new tags
insert into tag (name, icon, tag_group_id)
select t ->>'name', t->>'icon', p_id
from jsonb_array_elements(p_new_tags) as t;

-- Step 4: Update existing tags
update tag
set name = t.value ->>'name', icon = t.value->>'icon'
from jsonb_array_elements(p_updated_tags)
with ordinality as t(value, idx)
where tag.id::text = t.value->>'id';

end;
$$;

alter function edit_tag_group(integer, text, integer, text, jsonb, jsonb, uuid[]) owner to postgres;

grant
execute
on
function
edit_tag_group
(integer, text, integer, text, jsonb, jsonb, uuid[]) to anon;

grant execute on function edit_tag_group
(integer, text, integer, text, jsonb, jsonb, uuid[]) to authenticated;

grant execute on function edit_tag_group
(integer, text, integer, text, jsonb, jsonb, uuid[]) to service_role;

create function search_bundles(search_term text) returns SETOF bundle
    language sql
as
$$
select *
from bundle
where bundle_name ilike '%' || search_term || '%'
    or id::text ilike '%' || search_term || '%'
    or data->>'bundle_name' ilike '%' || search_term || '%'
    or data->>'bundle_info_code' ilike '%' || search_term || '%'
$$;

alter function search_bundles(text) owner to postgres;

grant
execute
on
function
search_bundles
(text) to anon;

grant execute on function search_bundles
(text) to authenticated;

grant execute on function search_bundles
(text) to service_role;

create function search_bundles_with_pagination(search_term text, from_index integer, to_index integer)
    returns TABLE
            (
                total_count integer,
                id          uuid,
                bundle_name text,
                data        json,
                created_at  timestamp with time zone
            )
    language plpgsql
as
$$
begin
return query with filtered as (
    select *
    from bundle
    where
      bundle.bundle_name ilike '%' || search_term || '%'
      or bundle.id::text ilike '%' || search_term || '%'
      or bundle.data->>'bundle_name' ilike '%' || search_term || '%'
      or bundle.data->>'bundle_info_code' ilike '%' || search_term || '%'
  ),
  counted as (
    select *, count(*) over() as total from filtered
  )
select counted.total as total_count, -- Rename counted.total to total_count
       counted.id,                   -- Keep counted.id as is
       counted.bundle_name,          -- Keep counted.bundle_name as is
       counted.data,                 -- Keep counted.data as is
       counted.created_at            -- Keep counted.created_at as is
from counted offset from_index limit (to_index - from_index + 1);
end;
$$;

alter function search_bundles_with_pagination(text, integer, integer) owner to postgres;

grant
execute
on
function
search_bundles_with_pagination
(text, integer, integer) to anon;

grant execute on function search_bundles_with_pagination
(text, integer, integer) to authenticated;

grant execute on function search_bundles_with_pagination
(text, integer, integer) to service_role;

create function search_bundles(p_search_term text, p_page integer DEFAULT 0,
                               p_page_size integer DEFAULT 10) returns json security definer
    language plpgsql
as
$$
DECLARE
v_offset INTEGER := p_page * p_page_size;
  v_items
JSON;
  v_total_count
INTEGER;
BEGIN
  -- Get the matching records with pagination
SELECT json_agg(t)
INTO
    v_items
FROM (SELECT *
      FROM bundle
      WHERE
          -- Search in id (converted to text)
          id::text ILIKE '%' || p_search_term || '%'
      -- Search in regular bundle_name column
      OR bundle_name ILIKE '%' || p_search_term || '%'
      -- Search in data->bundle_name
      OR data->>'bundle_name' ILIKE '%' || p_search_term || '%'
      -- Search in data->bundle_info_code
      OR data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
      ORDER BY bundle_name
          LIMIT p_page_size
      OFFSET v_offset) t;

-- Get the total count of matching records
SELECT COUNT(*)
INTO
    v_total_count
FROM bundle
WHERE id::text ILIKE '%' || p_search_term || '%'
    OR bundle_name ILIKE '%' || p_search_term || '%'
    OR data->>'bundle_name' ILIKE '%' || p_search_term || '%'
    OR data->>'bundle_info_code' ILIKE '%' || p_search_term || '%';

-- Handle case when no results found
IF
v_items IS NULL THEN
    v_items := '[]';
END IF;

  -- Return a JSON object with items and total count
RETURN json_build_object(
        'items', v_items,
        'total_count', v_total_count
       );
END;
$$;

alter function search_bundles(text, integer, integer) owner to postgres;

grant
execute
on
function
search_bundles
(text, integer, integer) to anon;

grant execute on function search_bundles
(text, integer, integer) to authenticated;

grant execute on function search_bundles
(text, integer, integer) to service_role;

create function get_unique_tags()
    returns TABLE
            (
                id    uuid,
                title text
            )
    language sql as
$$
select distinct t.id,
                t.name || ' (' || tg.name || ')' as title
from tag t
         join tag_group tg on tg.id = t.tag_group_id
         join bundle_tag bt on bt.tag_id = t.id
    $$;

alter function get_unique_tags() owner to postgres;

grant
execute
on
function
get_unique_tags
() to anon;

grant execute on function get_unique_tags
() to authenticated;

grant execute on function get_unique_tags
() to service_role;

create function get_tags_with_group(search text, page integer, page_size integer)
    returns TABLE
            (
                id    uuid,
                title text
            )
    language sql as
$$
select t.id,
       t.name || ' (' || tg.name || ')' as title
from tag t
         join tag_group tg on tg.id = t.tag_group_id
where t.name ilike '%' || search || '%'
order by t.name
    limit page_size
offset (page - 1) * page_size $$;

alter function get_tags_with_group(text, integer, integer) owner to postgres;

grant
execute
on
function
get_tags_with_group
(text, integer, integer) to anon;

grant execute on function get_tags_with_group
(text, integer, integer) to authenticated;

grant execute on function get_tags_with_group
(text, integer, integer) to service_role;

create function get_tags_with_group_all(search text, page integer, page_size integer) returns json
    language sql as
$$
select json_build_object(
               'total', (select count(*)
                         from tag t
                                  join tag_group tg on tg.id = t.tag_group_id
                         where t.name ilike '%' || search || '%' ),
    'items', (
      select json_agg(item)
      from (
        select
          t.id,
          t.name || ' (' || tg.name || ')' as title
        from tag t
        join tag_group tg on tg.id = t.tag_group_id
        where t.name ilike '%' || search || '%'
        order by t.name
        limit page_size
        offset (page - 1) * page_size
      ) as item
    )
  );
$$;

alter function get_tags_with_group_all(text, integer, integer) owner to postgres;

grant
execute
on
function
get_tags_with_group_all
(text, integer, integer) to anon;

grant execute on function get_tags_with_group_all
(text, integer, integer) to authenticated;

grant execute on function get_tags_with_group_all
(text, integer, integer) to service_role;

create function search_bundles(p_search_term text, p_page integer DEFAULT 0, p_page_size integer DEFAULT 10,
                               p_tag_ids uuid[] DEFAULT NULL ::uuid[]) returns json security definer
    language plpgsql
as
$$
DECLARE
v_offset INTEGER := p_page * p_page_size;
  v_items
JSON;
  v_total_count
INTEGER;
BEGIN
  -- Get matching records with optional tag filtering
SELECT json_agg(t)
INTO
    v_items
FROM (SELECT DISTINCT b.*
      FROM bundle b
               LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
      WHERE (
          p_search_term IS NULL OR
          b.id::text ILIKE '%' || p_search_term || '%' OR
        b.bundle_name ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
          )
        AND (
          p_tag_ids IS NULL OR cardinality(p_tag_ids) = 0 OR bt.tag_id = ANY (p_tag_ids)
          )
      ORDER BY b.bundle_name LIMIT p_page_size
      OFFSET v_offset) t;

-- Get total count with the same filtering
SELECT COUNT(DISTINCT b.id)
INTO
    v_total_count
FROM bundle b
         LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
WHERE (
    p_search_term IS NULL OR
    b.id::text ILIKE '%' || p_search_term || '%' OR
      b.bundle_name ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
    )
  AND (
    p_tag_ids IS NULL OR cardinality(p_tag_ids) = 0 OR bt.tag_id = ANY (p_tag_ids)
    );

-- Handle no result case
IF
v_items IS NULL THEN
    v_items := '[]';
END IF;

  -- Return results
RETURN json_build_object(
        'items', v_items,
        'total_count', v_total_count
       );
END;
$$;

alter function search_bundles(text, integer, integer, uuid[]) owner to postgres;

grant
execute
on
function
search_bundles
(text, integer, integer, uuid[]) to anon;

grant execute on function search_bundles
(text, integer, integer, uuid[]) to authenticated;

grant execute on function search_bundles
(text, integer, integer, uuid[]) to service_role;

create function search_bundle(p_search_term text, p_page integer DEFAULT 0, p_page_size integer DEFAULT 10) returns json security definer
    language plpgsql
as
$$
DECLARE
v_offset INTEGER := p_page * p_page_size;
  v_items
JSON;
  v_total_count
INTEGER;
BEGIN
  -- Get the matching records with pagination
SELECT json_agg(t)
INTO
    v_items
FROM (SELECT *
      FROM bundle
      WHERE
          -- Search in id (converted to text)
          id::text ILIKE '%' || p_search_term || '%'
      -- Search in regular bundle_name column
      OR bundle_name ILIKE '%' || p_search_term || '%'
      -- Search in data->bundle_name
      OR data->>'bundle_name' ILIKE '%' || p_search_term || '%'
      -- Search in data->bundle_info_code
      OR data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
      ORDER BY bundle_name
          LIMIT p_page_size
      OFFSET v_offset) t;

-- Get the total count of matching records
SELECT COUNT(*)
INTO
    v_total_count
FROM bundle
WHERE id::text ILIKE '%' || p_search_term || '%'
    OR bundle_name ILIKE '%' || p_search_term || '%'
    OR data->>'bundle_name' ILIKE '%' || p_search_term || '%'
    OR data->>'bundle_info_code' ILIKE '%' || p_search_term || '%';

-- Handle case when no results found
IF
v_items IS NULL THEN
    v_items := '[]';
END IF;

  -- Return a JSON object with items and total count
RETURN json_build_object(
        'items', v_items,
        'total_count', v_total_count
       );
END;
$$;

alter function search_bundle(text, integer, integer) owner to postgres;

grant
execute
on
function
search_bundle
(text, integer, integer) to anon;

grant execute on function search_bundle
(text, integer, integer) to authenticated;

grant execute on function search_bundle
(text, integer, integer) to service_role;

create function search_bundle(p_search_term text, p_page integer DEFAULT 0, p_page_size integer DEFAULT 10,
                              p_tag_ids uuid[] DEFAULT NULL ::uuid[]) returns json security definer
    language plpgsql
as
$$
DECLARE
v_offset INTEGER := p_page * p_page_size;
  v_items
JSON;
  v_total_count
INTEGER;
BEGIN
  -- Get matching records with optional tag filtering
SELECT json_agg(t)
INTO
    v_items
FROM (SELECT DISTINCT b.*
      FROM bundle b
               LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
      WHERE (
          p_search_term IS NULL OR
          b.id::text ILIKE '%' || p_search_term || '%' OR
        b.bundle_name ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
          )
        AND (
          p_tag_ids IS NULL OR bt.tag_id = ANY (p_tag_ids)
          )
      ORDER BY b.bundle_name LIMIT p_page_size
      OFFSET v_offset) t;

-- Get total count with the same filtering
SELECT COUNT(DISTINCT b.id)
INTO
    v_total_count
FROM bundle b
         LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
WHERE (
    p_search_term IS NULL OR
    b.id::text ILIKE '%' || p_search_term || '%' OR
      b.bundle_name ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
    )
  AND (
    p_tag_ids IS NULL OR bt.tag_id = ANY (p_tag_ids)
    );

-- Handle no result case
IF
v_items IS NULL THEN
    v_items := '[]';
END IF;

  -- Return results
RETURN json_build_object(
        'items', v_items,
        'total_count', v_total_count
       );
END;
$$;

alter function search_bundle(text, integer, integer, uuid[]) owner to postgres;

grant
execute
on
function
search_bundle
(text, integer, integer, uuid[]) to anon;

grant execute on function search_bundle
(text, integer, integer, uuid[]) to authenticated;

grant execute on function search_bundle
(text, integer, integer, uuid[]) to service_role;

create function get_translated_tag_by_tag_id_list(locale_param text, tag_ids uuid[])
    returns TABLE
            (
                id           uuid,
                tag_group_id bigint,
                name         character varying,
                icon         character varying,
                data         jsonb,
                created_at   timestamp without time zone,
                updated_at   timestamp without time zone
            )
    language plpgsql
as
$$
BEGIN
RETURN QUERY

SELECT t.id,
       t.tag_group_id,
       COALESCE(tt.name, t.name) AS name,
       t.icon,
       COALESCE(tt.data, t.data) AS data,
       t.created_at,
       t.updated_at
FROM tag t
         LEFT JOIN tag_translation tt
                   ON tt.tag_id = t.id
                       AND tt.locale = locale_param
WHERE t.id = ANY (tag_ids);


END;
$$;

alter function get_translated_tag_by_tag_id_list(text, uuid[]) owner to postgres;

grant
execute
on
function
get_translated_tag_by_tag_id_list
(text, uuid[]) to anon;

grant execute on function get_translated_tag_by_tag_id_list
(text, uuid[]) to authenticated;

grant execute on function get_translated_tag_by_tag_id_list
(text, uuid[]) to service_role;

create
or replace function get_translated_tag_by_tag_group_id(locale_param text, tag_group_id_param bigint)
    returns TABLE(id uuid, tag_group_id bigint, name character varying, icon character varying, data jsonb)
    language plpgsql
as
$$
BEGIN
RETURN QUERY
SELECT t.id,
       t.tag_group_id,
       COALESCE(tt.name, t.name) AS name,
       t.icon,
       COALESCE(tt.data, t.data) AS data
FROM tag t
         INNER JOIN public.bundle_tag bt on t.id = bt.tag_id
         INNER JOIN public.bundle b on b.id = bt.bundle_id
         LEFT JOIN tag_translation tt
                   ON tt.tag_id = t.id
                       AND tt.locale = locale_param
WHERE t.tag_group_id = tag_group_id_param
  AND b.is_active
GROUP BY 1, 2, 3, 4, 5;
END;
$$;

alter function get_translated_tag_by_tag_group_id(text, bigint) owner to postgres;

grant
execute
on
function
get_translated_tag_by_tag_group_id
(text, bigint) to anon;

grant execute on function get_translated_tag_by_tag_group_id
(text, bigint) to authenticated;

grant execute on function get_translated_tag_by_tag_group_id
(text, bigint) to service_role;

create function get_referral_transactions(p_user_id uuid)
    returns TABLE
            (
                id              uuid,
                created_at      timestamp with time zone,
                user_id         uuid,
                referral_code   text,
                payment_time    timestamp with time zone,
                currency        text,
                from_user_email text,
                to_user_email   text,
                amount          numeric
            )
    language plpgsql
as
$$
BEGIN
RETURN QUERY
SELECT o.id,
       o.created_at,
       o.user_id,
       o.referral_code,
       o.payment_time,
       o.currency,
       u_from.email AS from_user_email,
       u_to.email   AS to_user_email,
       pu.amount    AS amount
FROM user_order o
         INNER JOIN users_copy u_from ON u_from.metadata ->> 'referral_code' = o.referral_code
    INNER JOIN users_copy u_to
ON u_to.id = o.user_id
    INNER JOIN promotion_usage pu ON o.referral_code = pu.referral_code
WHERE
    o.user_id = p_user_id
  AND o.referral_code IS NOT NULL;
END;
$$;

alter function get_referral_transactions(uuid) owner to postgres;

grant
execute
on
function
get_referral_transactions
(uuid) to anon;

grant execute on function get_referral_transactions
(uuid) to authenticated;

grant execute on function get_referral_transactions
(uuid) to service_role;

create function get_referral_transactions(p_user_id uuid, p_limit integer, p_offset integer)
    returns TABLE
            (
                id              uuid,
                created_at      timestamp with time zone,
                user_id         uuid,
                referral_code   text,
                payment_time    timestamp with time zone,
                currency        text,
                from_user_email text,
                to_user_email   text,
                amount          numeric
            )
    language plpgsql
as
$$
BEGIN
RETURN QUERY
SELECT o.id,
       o.created_at,
       o.user_id,
       o.referral_code,
       o.payment_time,
       o.currency,
       u_from.email AS from_user_email,
       u_to.email   AS to_user_email,
       pu.amount    AS amount
FROM user_order o
         INNER JOIN users_copy u_from ON u_from.metadata ->> 'referral_code' = o.referral_code
    INNER JOIN users_copy u_to
ON u_to.id = o.user_id
    INNER JOIN promotion_usage pu ON o.referral_code = pu.referral_code
WHERE
    o.user_id = p_user_id
  AND o.referral_code IS NOT NULL
ORDER BY o.created_at DESC
    LIMIT p_limit
OFFSET p_offset;
END;
$$;

alter function get_referral_transactions(uuid, integer, integer) owner to postgres;

grant
execute
on
function
get_referral_transactions
(uuid, integer, integer) to anon;

grant execute on function get_referral_transactions
(uuid, integer, integer) to authenticated;

grant execute on function get_referral_transactions
(uuid, integer, integer) to service_role;

create function get_referral_transactions_with_count(p_user_id uuid, p_limit integer, p_offset integer) returns json
    language plpgsql
as
$$
DECLARE
v_total INT;
  v_data
JSON;
BEGIN
  -- Count total records
SELECT COUNT(*)
INTO v_total
FROM user_order
WHERE user_id = p_user_id
  AND referral_code IS NOT NULL;

-- Get paginated data
SELECT json_agg(t)
INTO v_data
FROM (SELECT o.id,
             o.created_at,
             o.user_id,
             o.referral_code,
             o.payment_time,
             o.currency,
             u_from.email AS from_user_email,
             u_to.email   AS to_user_email,
             pu.amount    AS amount
      FROM user_order o
               INNER JOIN users_copy u_from ON u_from.metadata ->> 'referral_code' = o.referral_code
          INNER JOIN users_copy u_to
      ON u_to.id = o.user_id
          INNER JOIN promotion_usage pu ON o.referral_code = pu.referral_code
      WHERE
          o.user_id = p_user_id
        AND o.referral_code IS NOT NULL
      ORDER BY o.created_at DESC
          LIMIT p_limit
      OFFSET p_offset) t;

-- Return final JSON
RETURN json_build_object(
        'total', v_total,
        'count', COALESCE(json_array_length(v_data), 0),
        'data', COALESCE(v_data, '[]'::json)
       );
END;
$$;

alter function get_referral_transactions_with_count(uuid, integer, integer) owner to postgres;

grant
execute
on
function
get_referral_transactions_with_count
(uuid, integer, integer) to anon;

grant execute on function get_referral_transactions_with_count
(uuid, integer, integer) to authenticated;

grant execute on function get_referral_transactions_with_count
(uuid, integer, integer) to service_role;

create function get_wallet_transactions_with_count(p_user_id uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 10,
                                                   p_offset integer DEFAULT 0) returns json
    language plpgsql
as
$$
declare
v_total int;
  v_data
json;
begin
  -- Count total
select count(*)
into v_total
from user_wallet_transaction as uwt
         inner join user_wallet as uw on uw.id = uwt.wallet_id
where p_user_id is null
   or uw.user_id = p_user_id;

-- Fetch paginated data
select json_agg(t)
into v_data
from (select uwt.id,
             uwt.wallet_id,
             uwt.amount,
             uwt.status,
             uwt.source,
             uwt.created_at
      from user_wallet_transaction as uwt
               inner join user_wallet as uw on uw.id = uwt.wallet_id
      where p_user_id is null
         or uw.user_id = p_user_id
      order by uwt.created_at desc limit p_limit
      offset p_offset) t;

return json_build_object(
        'total', v_total,
        'count', coalesce(json_array_length(v_data), 0),
        'data', coalesce(v_data, '[]'::json)
       );
end;
$$;

alter function get_wallet_transactions_with_count(uuid, integer, integer) owner to postgres;

grant
execute
on
function
get_wallet_transactions_with_count
(uuid, integer, integer) to anon;

grant execute on function get_wallet_transactions_with_count
(uuid, integer, integer) to authenticated;

grant execute on function get_wallet_transactions_with_count
(uuid, integer, integer) to service_role;

create function export_user_data(p_user_id uuid) returns json
    language plpgsql
as
$$
declare
v_devices json;
  v_referrals
json;
  v_wallet
json;
begin
  -- Devices
select json_agg(d)
into v_devices
from (select *
      from device
      where user_id = p_user_id
      order by created_at desc) d;

-- Referrals
select get_referral_transactions_with_count(p_user_id, 1000000, 0) -> 'data'
into v_referrals;

-- Wallet Transactions
select get_wallet_transactions_with_count(p_user_id, 1000000, 0) -> 'data'
into v_wallet;

-- Final JSON output
return json_build_object(
        'devices', coalesce(v_devices, '[]'::json),
        'referrals', coalesce(v_referrals, '[]'::json),
        'wallet_transactions', coalesce(v_wallet, '[]'::json)
       );
end;
$$;

alter function export_user_data(uuid) owner to postgres;

grant
execute
on
function
export_user_data
(uuid) to anon;

grant execute on function export_user_data
(uuid) to authenticated;

grant execute on function export_user_data
(uuid) to service_role;

create function update_promotion_rule_name() returns trigger
    language plpgsql
as
$$
DECLARE
action_name TEXT;
  event_name
TEXT;
BEGIN
SELECT name
INTO action_name
FROM promotion_rule_action
WHERE id = NEW.promotion_rule_action_id;
SELECT name
INTO event_name
FROM promotion_rule_event
WHERE id = NEW.promotion_rule_event_id;

NEW
.
name
:= action_name || '-' || event_name || '-' || NEW.max_usage::text;
RETURN NEW;
END;
$$;

alter function update_promotion_rule_name() owner to postgres;

grant
execute
on
function
update_promotion_rule_name
() to anon;

grant execute on function update_promotion_rule_name
() to authenticated;

grant execute on function update_promotion_rule_name
() to service_role;

create function validate_bundle_codes() returns trigger
    language plpgsql
as
$$
DECLARE
code TEXT;
    exists_count
INT;
BEGIN
    -- Only validate if bundle_code is NOT NULL and NOT empty
    IF
NEW.bundle_code IS NULL OR trim(NEW.bundle_code) = '' THEN
        RETURN NEW;
END IF;

    -- Split bundle_code string into array
    FOREACH
code IN ARRAY string_to_array(NEW.bundle_code, ',')
    LOOP
SELECT COUNT(*)
INTO exists_count
FROM bundle
WHERE data ->>'bundle_code' = trim (code);

IF
exists_count = 0 THEN
            RAISE EXCEPTION 'Invalid bundle code: %', code;
END IF;
END LOOP;

RETURN NEW;
END;
$$;

alter function validate_bundle_codes() owner to postgres;

grant
execute
on
function
validate_bundle_codes
() to anon;

grant execute on function validate_bundle_codes
() to authenticated;

grant execute on function validate_bundle_codes
() to service_role;

create function get_referral_transactions_with_count(p_user_id uuid DEFAULT NULL::uuid, p_limit integer DEFAULT 10,
                                                     p_offset integer DEFAULT 0,
                                                     p_search text DEFAULT NULL::text) returns json
    language plpgsql
as
$$
DECLARE
v_total INT;
  v_data
JSON;
BEGIN
  -- Count total records
SELECT COUNT(*)
INTO v_total
FROM user_order o
WHERE (p_user_id IS NULL OR o.user_id = p_user_id)
  AND o.referral_code IS NOT NULL
  AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%');

-- Get paginated data
SELECT json_agg(t)
INTO v_data
FROM (SELECT o.id,
             o.created_at,
             o.user_id,
             o.referral_code,
             o.payment_time,
             o.currency,
             o.modified_amount,
             o.order_status,
             u_from.email AS from_user_email,
             u_to.email   AS to_user_email,
             pu.status,
             pu.amount    AS amount
      FROM user_order o
               INNER JOIN users_copy u_from ON u_from.metadata ->> 'referral_code' = o.referral_code
          INNER JOIN users_copy u_to
      ON u_to.id = o.user_id
          INNER JOIN promotion_usage pu ON o.referral_code = pu.referral_code
      WHERE
          (p_user_id IS NULL
         OR o.user_id = p_user_id)
        AND o.referral_code IS NOT NULL
        AND (p_search IS NULL
         OR o.referral_code ILIKE '%' || p_search || '%')
      ORDER BY o.created_at DESC
          LIMIT p_limit
      OFFSET p_offset) t;

-- Return final JSON
RETURN json_build_object(
        'total', v_total,
        'count', COALESCE(json_array_length(v_data), 0),
        'data', COALESCE(v_data, '[]'::json)
       );
END;
$$;

alter function get_referral_transactions_with_count(uuid, integer, integer, text) owner to postgres;

grant
execute
on
function
get_referral_transactions_with_count
(uuid, integer, integer, text) to anon;

grant execute on function get_referral_transactions_with_count
(uuid, integer, integer, text) to authenticated;

grant execute on function get_referral_transactions_with_count
(uuid, integer, integer, text) to service_role;

create function export_referrals_data(p_user_id uuid DEFAULT NULL::uuid, p_search text DEFAULT NULL::text) returns json
    language plpgsql
as
$$
DECLARE
v_user_id UUID := NULLIF(p_user_id::text, '')::uuid;
  v_total
INT;
  v_data
JSON;
BEGIN
  -- Count total records
SELECT COUNT(*)
INTO v_total
FROM user_order o
WHERE (v_user_id IS NULL OR o.user_id = v_user_id)
  AND o.referral_code IS NOT NULL
  AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%');

-- Get ALL data
SELECT json_agg(t)
INTO v_data
FROM (SELECT o.id,
             o.created_at,
             o.user_id,
             o.referral_code,
             o.payment_time,
             o.currency,
             u_from.email AS from_user_email,
             u_to.email   AS to_user_email,
             pu.amount    AS amount
      FROM user_order o
               INNER JOIN users_copy u_from ON u_from.metadata ->> 'referral_code' = o.referral_code
          INNER JOIN users_copy u_to
      ON u_to.id = o.user_id
          INNER JOIN promotion_usage pu ON o.referral_code = pu.referral_code
      WHERE
          (v_user_id IS NULL
         OR o.user_id = v_user_id)
        AND o.referral_code IS NOT NULL
        AND (p_search IS NULL
         OR o.referral_code ILIKE '%' || p_search || '%')
      ORDER BY o.created_at DESC) t;

RETURN json_build_object(
        'total', v_total,
        'count', COALESCE(json_array_length(v_data), 0),
        'referrals', COALESCE(v_data, '[]'::json)
       );
END;
$$;

alter function export_referrals_data(uuid, text) owner to postgres;

grant
execute
on
function
export_referrals_data
(uuid, text) to anon;

grant execute on function export_referrals_data
(uuid, text) to authenticated;

grant execute on function export_referrals_data
(uuid, text) to service_role;

CREATE
OR REPLACE FUNCTION get_active_tag_names_and_data_by_group(_tag_group_id integer)
RETURNS TABLE(id uuid,tag_group_id int,name text,icon text, data jsonb)
LANGUAGE sql
AS $$
SELECT t.id, t.tag_group_id, t.name, t.icon, t.data
FROM tag t
         INNER JOIN bundle_tag bt ON t.id = bt.tag_id
         INNER JOIN bundle b ON bt.bundle_id = b.id
WHERE t.tag_group_id = _tag_group_id
  AND b.is_active
GROUP BY t.id, t.tag_group_id, t.name, t.icon, t.data
ORDER BY t.name;
$$;


create table user_otp
(
    id         serial
        primary key,
    email      varchar(100) default NULL::character varying,
    mobile     varchar(100) default NULL::character varying,
    otp        varchar(6) not null,
    expire_at  timestamp,
    is_used    boolean      default false,
    created_at timestamp    default CURRENT_TIMESTAMP
);

alter table user_otp
    owner to postgres;

create index idx_user_otp_mobile
    on user_otp (mobile);

create index idx_user_otp_otp
    on user_otp (otp);


INSERT INTO tag_group("id", "name", "type", "is_active", "created_at", "updated_at", "group_category")
VALUES ('1', 'Countries', '1', 'true', now(), now(), 'on_land'),
       ('2', 'Regions', '1', 'true', now(), now(), 'on_land'),
       ('3', 'Cruise', '1', 'true', now(), now(), 'at_sea'),
       ('4', 'Global', '2', 'true', now(), now(), 'on_land');


create trigger on_auth_users_changed
after insert or update or delete on auth.users
for each row execute function public.sync_users_copy();

insert into users_copy (id,email,metadata) (select id,email, raw_user_meta_data from auth.users);




INSERT INTO "public"."promotion_rule_action" ("id", "name")
VALUES ('1', 'DISCOUNT_AMOUNT'),
       ('2', 'DISCOUNT_PERCENTAGE'),
       ('3', 'CASHBACK_AMOUNT'),
       ('4', 'CASHBACK_PERCENTAGE');

INSERT INTO "public"."promotion_rule_event" ("id", "name")
VALUES ('1', 'CREATE_ORDER'),
       ('2', 'CREATE_ACCOUNT');


CREATE POLICY "Enable read access for all users" ON "storage"."objects"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all users" ON "storage"."objects"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON "storage"."objects"
AS PERMISSIVE FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

CREATE POLICY "Enable delete for all users" ON "storage"."objects"
AS PERMISSIVE FOR DELETE
TO public
USING (true);

CREATE POLICY "Enable read access for all users" ON "storage"."buckets"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all users " ON "storage"."buckets"
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON "storage"."buckets"
AS PERMISSIVE FOR UPDATE
TO public
USING (true)
WITH CHECK (true);

CREATE POLICY "Enable delete for all users" ON "storage"."buckets"
AS PERMISSIVE FOR DELETE
TO public
USING (true);


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'unique_bundle_tag'
    ) THEN
        ALTER TABLE bundle_tag
        ADD CONSTRAINT unique_bundle_tag UNIQUE (bundle_id, tag_id);
    END IF;
END$$;



create or replace function insert_group_with_tags(
  _name text,
  _group_category text,
  _type integer,
  _tags jsonb
)
returns json
language plpgsql
as $$
declare
  inserted_group tag_group;
  tag jsonb;
begin
  insert into tag_group (name, group_category, type)
  values (_name, _group_category, _type)
  returning * into inserted_group;

  -- Insert tags
  for tag in select * from jsonb_array_elements(_tags)
  loop
    insert into tag (name, icon, tag_group_id)
    values (
      tag->>'name',
      tag->>'icon',
      inserted_group.id
    );
  end loop;

  return json_build_object('group', inserted_group);

exception
  when others then
    raise notice 'Rollback due to error: %', sqlerrm;
    -- No need for explicit ROLLBACK; PostgreSQL will auto-rollback the function on exception
    return json_build_object('error', sqlerrm);
end;
$$;


create or replace function delete_group_if_no_bundle(_group_id integer)
returns json
language plpgsql
as $$
declare
  bundle_count integer;
begin
  -- Count bundles associated via bundle_tag → tag → group
  select count(*)
  into bundle_count
  from bundle_tag bt
  join tag t on t.id = bt.tag_id
  where t.tag_group_id = _group_id;

  -- If bundles are found, return error
  if bundle_count > 0 then
    return json_build_object(
      'error', 'Cannot delete group: some tags are associated with bundles',
      'code', 'linked-bundles',
      'bundle_count', bundle_count
    );
  end if;

  -- Safe to delete group
  delete from tag_group where id = _group_id;

  return json_build_object('success', true);
exception
  when others then
    return json_build_object('error', sqlerrm, 'code', 500);
end;
$$;


create or replace function edit_tag_group(
  p_id integer,
  p_name text,
  p_type integer,
  p_group_category text,
  p_new_tags jsonb,
  p_updated_tags jsonb,
  p_deleted_tag_ids uuid[]
)
returns void
language plpgsql
as $$
begin
  -- Step 1: Update the tag group
  update tag_group
  set name = p_name,
      type = p_type,
      group_category = p_group_category
  where id = p_id;

  -- Step 2: Delete tags by IDs
  if array_length(p_deleted_tag_ids, 1) is not null then
    delete from tag
    where id = any(p_deleted_tag_ids);
  end if;

  -- Step 3: Insert new tags
  insert into tag (name, icon, tag_group_id)
  select
    t->>'name',
    t->>'icon',
    p_id
  from jsonb_array_elements(p_new_tags) as t;

  -- Step 4: Update existing tags
  update tag
  set
    name = t.value->>'name',
    icon = t.value->>'icon'
  from jsonb_array_elements(p_updated_tags) with ordinality as t(value, idx)
  where tag.id::text = t.value->>'id';

end;
$$;


create or replace function get_tags_with_group_all(
  search text,
  page integer,
  page_size integer
)
returns json
language sql
as $$
  select json_build_object(
    'total', (
      select count(*)
      from tag t
      join tag_group tg on tg.id = t.tag_group_id
      where t.name ilike '%' || search || '%'
    ),
    'items', (
      select json_agg(item)
      from (
        select
          t.id,
          t.name || ' (' || tg.name || ')' as title
        from tag t
        join tag_group tg on tg.id = t.tag_group_id
        where t.name ilike '%' || search || '%'
        order by t.name
        limit page_size
        offset (page - 1) * page_size
      ) as item
    )
  );
$$;


CREATE OR REPLACE FUNCTION search_bundles(
  p_search_term TEXT,
  p_page INTEGER DEFAULT 0,
  p_page_size INTEGER DEFAULT 10,
  p_tag_ids UUID[] DEFAULT NULL -- New parameter
)
RETURNS JSON AS $$
DECLARE
  v_offset INTEGER := p_page * p_page_size;
  v_items JSON;
  v_total_count INTEGER;
BEGIN
  -- Get matching records with optional tag filtering
  SELECT
    json_agg(t)
  INTO
    v_items
  FROM (
    SELECT DISTINCT b.*
    FROM bundle b
    LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
    WHERE
      (
        p_search_term IS NULL OR
        b.id::text ILIKE '%' || p_search_term || '%' OR
        b.bundle_name ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
        b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
      )
      AND (
        p_tag_ids IS NULL OR cardinality(p_tag_ids) = 0 OR bt.tag_id = ANY(p_tag_ids)
      )
    ORDER BY b.bundle_name
    LIMIT p_page_size
    OFFSET v_offset
  ) t;

  -- Get total count with the same filtering
  SELECT
    COUNT(DISTINCT b.id)
  INTO
    v_total_count
  FROM bundle b
  LEFT JOIN bundle_tag bt ON b.id = bt.bundle_id
  WHERE
    (
      p_search_term IS NULL OR
      b.id::text ILIKE '%' || p_search_term || '%' OR
      b.bundle_name ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_name' ILIKE '%' || p_search_term || '%' OR
      b.data->>'bundle_info_code' ILIKE '%' || p_search_term || '%'
    )
    AND (
      p_tag_ids IS NULL OR cardinality(p_tag_ids) = 0 OR bt.tag_id = ANY(p_tag_ids)
    );

  -- Handle no result case
  IF v_items IS NULL THEN
    v_items := '[]';
  END IF;

  -- Return results
  RETURN json_build_object(
    'items', v_items,
    'total_count', v_total_count
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;




CREATE OR REPLACE FUNCTION get_referral_transactions_with_count(
  p_user_id UUID DEFAULT NULL,
  p_limit INT DEFAULT 10,
  p_offset INT DEFAULT 0,
  p_search TEXT DEFAULT NULL,
  p_from_email TEXT DEFAULT NULL,
  p_referral_date DATE DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_total INT;
  v_data JSON;
BEGIN
  -- Count total records (only successful orders)
  SELECT COUNT(*) INTO v_total
  FROM user_order o
  INNER JOIN promotion_usage pu
    ON o.id = pu.order_id
  WHERE (p_user_id IS NULL OR o.user_id = p_user_id)
    AND o.referral_code IS NOT NULL
    AND o.order_status = 'success'
    AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%')
    AND (p_from_email IS NULL OR pu.referred_to ILIKE '%' || p_from_email || '%')
    AND (p_referral_date IS NULL OR o.created_at::date = p_referral_date);

  -- Get paginated data (only successful orders)
  SELECT json_agg(t) INTO v_data
  FROM (
    SELECT
      o.id,
      o.created_at,
      o.user_id,
      o.referral_code,
      o.payment_time,
      o.currency,
      o.modified_amount,
      o.order_status,
      pu.status,
      pu.amount AS amount,
      pu.referred_to,
      u.email AS user_email   -- only email for pu.user_id
    FROM
      user_order o
      INNER JOIN promotion_usage pu
        ON o.id = pu.order_id
      INNER JOIN users_copy u
        ON u.id = pu.user_id
    WHERE
      (p_user_id IS NULL OR o.user_id = p_user_id)
      AND o.referral_code IS NOT NULL
      AND o.order_status = 'success'
      AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%')
      AND (p_from_email IS NULL OR pu.referred_to ILIKE '%' || p_from_email || '%')
      AND (p_referral_date IS NULL OR o.created_at::date = p_referral_date)
    ORDER BY o.created_at DESC
    LIMIT p_limit OFFSET p_offset
  ) t;

  -- Return final JSON
  RETURN json_build_object(
    'total', v_total,
    'count', COALESCE(json_array_length(v_data), 0),
    'data', COALESCE(v_data, '[]'::json)
  );
END;
$$ LANGUAGE plpgsql;



   create or replace function get_wallet_transactions_with_count(
  p_user_id uuid default null,
  p_limit int default 10,
  p_offset int default 0
)
returns json as $$
declare
  v_total int;
  v_data json;
begin
  -- Count total
  select count(*) into v_total
  from user_wallet_transaction as uwt
  inner join user_wallet as uw on uw.id = uwt.wallet_id
  where p_user_id is null or uw.user_id = p_user_id;

  -- Fetch paginated data
  select json_agg(t) into v_data
  from (
    select
      uwt.id,
      uwt.wallet_id,
      uwt.amount,
      uwt.status,
      uwt.source,
      uw.currency,
      uwt.created_at
    from user_wallet_transaction as uwt
    inner join user_wallet as uw on uw.id = uwt.wallet_id
    where p_user_id is null or uw.user_id = p_user_id
    order by uwt.created_at desc
    limit p_limit offset p_offset
  ) t;

  return json_build_object(
    'total', v_total,
    'count', coalesce(json_array_length(v_data), 0),
    'data', coalesce(v_data, '[]'::json)
  );
end;
$$ language plpgsql;


   -- Create or replace the trigger function
CREATE OR REPLACE FUNCTION update_promotion_rule_name()
RETURNS TRIGGER AS $$
DECLARE
  action_name TEXT;
  event_name TEXT;
BEGIN
  SELECT name INTO action_name FROM promotion_rule_action WHERE id = NEW.promotion_rule_action_id;
  SELECT name INTO event_name FROM promotion_rule_event WHERE id = NEW.promotion_rule_event_id;

  NEW.name := action_name || '-' || event_name || '-' || NEW.max_usage::text;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger on promotion_rule table
DROP TRIGGER IF EXISTS trg_update_promotion_rule_name ON promotion_rule;

CREATE TRIGGER trg_update_promotion_rule_name
BEFORE INSERT OR UPDATE ON promotion_rule
FOR EACH ROW
EXECUTE FUNCTION update_promotion_rule_name();


CREATE OR REPLACE FUNCTION validate_bundle_codes()
RETURNS TRIGGER AS $$
DECLARE
    code TEXT;
    exists_count INT;
BEGIN
    -- Only validate if bundle_code is NOT NULL and NOT empty
    IF NEW.bundle_code IS NULL OR trim(NEW.bundle_code) = '' THEN
        RETURN NEW;
    END IF;

    -- Split bundle_code string into array
    FOREACH code IN ARRAY string_to_array(NEW.bundle_code, ',')
    LOOP
        SELECT COUNT(*) INTO exists_count
        FROM bundle
        WHERE data->>'bundle_code' = trim(code);

        IF exists_count = 0 THEN
            RAISE EXCEPTION 'Invalid bundle code: %', code;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER validate_bundle_codes_promo_trigger
BEFORE INSERT OR UPDATE ON promotion
FOR EACH ROW
EXECUTE FUNCTION validate_bundle_codes();


CREATE OR REPLACE FUNCTION export_referrals_data(
  p_user_id UUID DEFAULT NULL,
  p_search TEXT DEFAULT NULL,
  p_from_email TEXT DEFAULT NULL,
  p_referral_date DATE DEFAULT NULL
)
RETURNS JSON AS $$
DECLARE
  v_user_id UUID := NULLIF(p_user_id::text, '')::uuid;
  v_total INT;
  v_data JSON;
BEGIN
  -- Count total records (only successful orders)
  SELECT COUNT(*) INTO v_total
  FROM user_order o
  INNER JOIN promotion_usage pu
    ON o.id = pu.order_id
  WHERE (v_user_id IS NULL OR o.user_id = v_user_id)
    AND o.referral_code IS NOT NULL
    AND o.order_status = 'success'
    AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%')
    AND (p_from_email IS NULL OR pu.referred_to ILIKE '%' || p_from_email || '%')
    AND (p_referral_date IS NULL OR o.created_at::date = p_referral_date);

  -- Get ALL data (only successful orders)
  SELECT json_agg(t) INTO v_data
  FROM (
    SELECT
      o.id,
      o.created_at,
      o.user_id,
      o.referral_code,
      o.payment_time,
      o.currency,
      o.modified_amount,
      o.order_status,
      pu.status,
      pu.amount AS amount,
      pu.referred_to,
      u.email AS user_email   -- only email of pu.user_id
    FROM
      user_order o
      INNER JOIN promotion_usage pu
        ON o.id = pu.order_id
      INNER JOIN users_copy u
        ON u.id = pu.user_id
    WHERE
      (v_user_id IS NULL OR o.user_id = v_user_id)
      AND o.referral_code IS NOT NULL
      AND o.order_status = 'success'
      AND (p_search IS NULL OR o.referral_code ILIKE '%' || p_search || '%')
      AND (p_from_email IS NULL OR pu.referred_to ILIKE '%' || p_from_email || '%')
      AND (p_referral_date IS NULL OR o.created_at::date = p_referral_date)
    ORDER BY o.created_at DESC
  ) t;

  RETURN json_build_object(
    'total', v_total,
    'count', COALESCE(json_array_length(v_data), 0),
    'referrals', COALESCE(v_data, '[]'::json)
  );
END;
$$ LANGUAGE plpgsql;


   DO $$
BEGIN
    -- Check if the constraint already exists
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'unique_bundle_tag'
    ) THEN
        ALTER TABLE bundle_tag
        ADD CONSTRAINT unique_bundle_tag UNIQUE (bundle_id, tag_id);
    END IF;
END $$;


CREATE OR REPLACE FUNCTION public.get_bundles_for_tag(p_tag_id uuid)
    RETURNS TABLE
            (
                id          uuid,
                data        jsonb,
                is_active   bool,
                created_at  timestamp,
                updated_at  timestamp,
                bundle_name text
            )
    language plpgsql
as
$$
BEGIN
    RETURN QUERY
        SELECT b.id,
               b.data,
               b.is_active,
               b.created_at,
               b.updated_at,
               b.bundle_name
        FROM bundle b
                 INNER JOIN bundle_tag bt ON bt.bundle_id = b.id
        WHERE bt.tag_id = p_tag_id;
END;
$$;